### ISSUE TITLE
Missing 'linux/linuxjoystick.h'

### ISSUE THREAD

**Issue by Semicolon1304** [pspdev/psptoolchain#133]
I'm trying to compile on OS X El Capitan (10.11.6) and I get the following error:

`remotejoy.c:27:10: fatal error: 'linux/joystick.h' file not found`

I have no idea what this means or what I'm doing wrong. any suggestions?

**Comment by sharkwouter** [comment]
Thanks for the report. Are you installing using sudo? If so, you could try installing with the following command instead:
```
sudo ./toolchain-sudo.sh $(seq 1 8) $(seq 10 13)
```
Then it will install everything apart from psplink.

This is happening here it seems: https://github.com/pspdev/psplinkusb/blob/01b73b596f9cdba71e328ae08b979b14af161997/tools/remotejoy/pc/remotejoy.c#L27
I'm not sure how we'd solve this. I've not seen this issue being reported before, which is strange since we didn't really change anything in psplink recently iirc.

**Comment by Semicolon1304** [comment]
Thanks! everything worked perfectly!

**Comment by carstene1ns** [comment]
This is usually a problem with missing 'sdl-config':
https://github.com/pspdev/psplinkusb/blob/master/Makefile.clients#L10

**Comment by sharkwouter** [comment]
Guess sdl1.2 is required after all. We should probably make the prepare script install it then :/
