### ISSUE TITLE
pspsh fails to compile with gcc 4.8.1

### ISSUE THREAD

**Issue by RenaKunisaki** [pspdev/psptoolchain#47]
pspsh compile error on Lubuntu 13.10 AMD64:

```
$ sudo ./toolchain-sudo.sh 
[...lots of compiling...]
pspsh.C: In function ‘int strlen_cmd(int, char**)’:
pspsh.C:439:50: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
  snprintf(val, sizeof(val), "%d", strlen(argv[0]));
                                                  ^
pspsh.C:439:50: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type         ‘size_t {aka long unsigned int}’ [-Wformat=]
pspsh.C: In function ‘char* command_gen(const char*, int)’:
pspsh.C:693:13: warning: variable ‘locals’ set but not used [-Wunused-but-set-variable]
  static int locals;
             ^
pspsh.C: In function ‘void shutdown_app()’:
pspsh.C:1985:38: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
   free(rl_basic_word_break_characters);
                                      ^
In file included from pspsh.C:15:0:
/usr/include/stdlib.h:482:13: error:   initializing argument 1 of ‘void free(void*)’ [-fpermissive]
 extern void free (void *__ptr) __THROW;
             ^
make[1]: *** [pspsh.o] Error 1
make[1]: Leaving directory `/home/rena/dev/psp/psptoolchain/build/psplinkusb/pspsh'
make: *** [all] Error 2
../scripts/009-psplinkusb.sh: Failed.
ERROR: Could not run the toolchain script.
```
